# Generated by Django 4.0.4 on 2022-06-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_courseteacher_options_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description_as_markdown',
            field=models.BooleanField(default=False, verbose_name='As markdown'),
        ),
    ]
